version: '3'
services:
  mytopapi:
    image: amer1candocker/mytop-demo
    container_name: mytopapi
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
    links:
      - mongodb
  mongodb:
    image: mongo:4.4.4
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data-4.4:/data/db
    command: --wiredTigerCacheSizeGB 1.5



#version: "3"
#services:
#  node-serv:
#    container_name: node-serv
#    image: node-serv
#    restart: always
#    build: .
#    ports:
#      - "8080:8080"
#    links:
#      - db
#  db:
#    container_name: db
#    image: mongo
#    ports:
#      - '27017:27017'
