version: '3'
services:
  mytopapi:
    image: amer1candocker/mytop-demo
    container_name: mytopapi
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/opt/app/.env
    links:
      - mongodb
  mongodb:
    image: mongo:4.4.4
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongodb:/data/db
    command: --wiredTigerCacheSizeGB 1.5
