version: '3'
services:
  dbmongo:
    image: mongo:latest
    container_name: dbmongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - ./mongodb:/data/db
    command: --wiredTigerCacheSizeGB 1.5
  mytopapi:
    image: amer1candocker/mytop-demo
    container_name: mytopapi
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/opt/app/.env
    links:
      - dbmongo

