  name: Publish Docker

  on:
    push:
      branches: [master]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Publish to registry
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            name: amer1can/mytop-demo
            access-token: ${{ secrets.ACCESS_TOKEN }}
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
